### PR TITLE
support for mac and linux

### LINKED ISSUE #4: xplat support

### PR DESCRIPTION
**Pull request by tugberkugurlu**
Fixes #4 :fireworks: :boom: :dancers: :dancer: 

It happily runs on Linux and I will just assume that it runs on Mac as well. It just looks and see what the OS is and if it's not windows, it runs on Kestrel. There are some weird stuff like stopping the server gives an exception on dispose, kestrel doesn't log the host and port but minor stuff. Added some logging on the console to indicate start and shut down, it should help:

image

image

### CODE REVIEW

**Comment by luisrudge** [comment]
@tugberkugurlu  why not use kestrel in windows too?

**Comment by tugberkugurlu** [comment]
@luisrudge WebListener is more stable and mature than kestrel AFAIK. However, it shouldn't matter for this project that much as it's dev-only but kestrel seems a bit clunky to me (not being able to dispose, etc.). More info: https://vimeo.com/131631887

OTOH, as a user, it should be transparent to you. Any specific reason you want kestrel in windows, too?

**Comment by luisrudge** [comment]
nope. Just less code to maintain :D

**Comment by luisrudge** [comment]
Well. scratch that. you don't have to maintain nothing, just an if/else :D I forgive you haha :)

**Comment by tugberkugurlu** [comment]
:smile:

**Pull request merged**
